[package]
name = "newsletter"
version = "0.1.0"
authors = ["Andreas Monitzer <andreas@monitzer.com>"]
edition = "2018"

[dependencies]
rocket = "0.4"

[dependencies.rusqlite]
version = "0.18.0"
features = ["bundled"]
